---
fontsize: 11pt
geometry: margin=1in
header-includes:
  - \usepackage{lineno}
  - \linenumbers
  - \usepackage{setspace}
  - \usepackage{todonotes}
  - \doublespacing
  - \usepackage{rotating}
  - \usepackage{color, soul}
  - \usepackage[document]{ragged2e}
  - \usepackage[sc]{mathpazo}
layout: 11pt
linkcolor: black
output:
  pdf_document:
    fig_caption: yes
    keep_tex: no
urlcolor: black
---


\begin{singlespace}

\begin{center}

\large{\textbf{Quantifying the limits to forecasting the Yellowstone bison population}}

\renewcommand*{\thefootnote}{\fnsymbol{footnote}}

\vspace{1em}

\normalsize{Andrew T. Tredennick\textsuperscript{1}}

\vspace{1em}

\textit{\small{\textsuperscript{1}Department of Wildland Resources and the Ecology Center, 5230 Old Main Hill, Utah State University, Logan, Utah 84322 USA}}

\end{center}

\vspace{2em}

\textbf{Running Head}: Limits to bison forecasting

\textbf{Corresponding Author}: \\
\hspace{2em}Andrew Tredennick \\  
\hspace{2em}Department of Wildland Resources and the Ecology Center\\
\hspace{2em}Utah State University \\
\hspace{2em}5230 Old Main Hill \\
\hspace{2em}Logan, Utah 84322 USA \\
\hspace{2em}Phone: +1-970-443-1599 \\
\hspace{2em}Fax: +1-435-797-3796 \\
\hspace{2em}Email: atredenn@gmail.com

\end{singlespace}
\renewcommand*{\thefootnote}{\arabic{footnote}}
\setcounter{footnote}{0}

\newpage{}

\begin{abstract}
Write something here...

\vspace{1em}

\emph{Key words: Bayesian state-space model;} Bison bison\emph{; ecological forecasting; population model; Yellowstone National Park, USA; uncertainty.}

\end{abstract}


# Introduction

# Materials and Methods

##  Data
Aerial counts of the Yellowstone bison population from 1970-2017 (Fig. 1A) were used to estimate model parameters and states.
Counts typically occurred four times a year.
We used summer counts only because the summer aggregation of bison tends to produce more accurate counts (Hobbs et al. 2015).
Replicate counts were taken in 41 of the 48 years, and from these replicates we estimated the mean annual total population in the park and the annual standard deviation of counts (i.e., observation error).

We used mean annual snow water equivalent (SWE, mm) as an environmental covariate in our population model.
SWE data came from the West Yellowstone SNOTEL station (Site #924).
We downloaded the SNOTEL data using the ```snotelr``` package in R and then calculated the mean SWE for each year.

##  State-space model
We used a Bayesian state-space model to obtain posterior distributions of all unknown parameters, latent states, and forecasts of future states.
The fully specified model, including a model of the ecological process, a model linking the process to the data, and parameter models, takes the form:

\vspace{-2em}

\begin{align}
\left[ \boldsymbol{\theta}_\text{p}, z_{(t)}, z_{(t-1)} | y_{(t)}, x_{(t)}, \sigma^2_{\text{obs.,(t)}} \right ] &\propto \prod_{t=2}^{58} \underbrace{\left[ z_{(t)} | \boldsymbol{\theta}_\text{p}, z_{(t-1)}, x_{(t)} \right]}_{\text{process}} \prod_{t=1}^{48} \underbrace{\left[ y_{(t)} | \sigma^2_{\text{obs.,(t)}}, z_{(t)} \right]}_{\text{data}} \underbrace{\left[ \boldsymbol{\theta}_\text{p}, z_{(t=1)}\right]}_{\text{parameters}},
\end{align}

where the notation $[a|b,c]$ reads as the probability or probability density of *a* conditional on *b* and *c* (Hobbs and Hooten 2015).
$\boldsymbol{\theta}_\text{p}$ is a vector of parameters in the process model, $z_{(t)}$ is the latent, or unobservable and true, state of the bison population abundance at time *t*, $y_{(t)}$ is the observed state of bison population abundance at time *t*, and $x_{(t)}$ is the standardized value of mean annual SWE at time *t*.
Note that the product associated with the "process model" applies over 10 more years than the product associated with the "data model."
The extra ten years are forecasts of the latent state ten years into the future, for which no likelihood can be calculated.

Our process model represents the population dynamics of the Yellowstone bison using the stochastic model

\vspace{-2em}

\begin{align}
z_{(t)} \sim \text{lognormal}\left( \text{log}\left(z_{(t-1)}e^{r + b_0 z_{(t-1)} + b_1 x_{(t)}}\right), \sigma^2_\text{p} \right),
\end{align}

where the determinstic model $z_{(t-1)}e^{r + b_0 z_{(t-1)} + b_1 x_{(t)}}$ is a Ricker model of population growth (Ricker 19xx) that predicts the mean of $z_{(t)}$ on the log scale as function of the true state of the population at time $t-1$ ($z_{(t-1)}$), the intrinsic, per capita rate of increase (*r*), the strength of density-dependence ($b_0$), and the effect ($b_1$) of mean annual snow water equivalent at time *t* ($x_{(t)}$).
The quantity $\sigma^2_\text{p}$ is the process variance on the log scale, which accounts for all the drivers of the true state that are not found in the determinstic model.

Our state-space model requires prior distributions for all parameters and for the initial condition of $z$.
We used an informative prior for the intrinsic growth rate, $r$, based on the population growth ($\lambda$) reported by Hobbs et al. (2015).
The Hobbs et al. (2015) model includes estimates of two population growth rates, one for populations infected with brucellosis and one for populations not infected with brucellosis.
Although the population growth rate was depressed in brucellosis-infected populations, the posterior estimate of the difference between the two growth rates overlapped zero, indicating little support for differentiating among the two.
We therefore chose to use the estimates for the brucellosis-free population: mean $= 1.11$ and s.d. $=0.0241$.
We converted $\lambda$, the population growth rate, to $r$, the per capita rate of increase, by log-transforming $\lambda$: $r = \text{log}(\lambda) = 0.1$.
To get the standard deviation on the same scale, we simulated 100,000 numbers from the distribution $\log(\text{Normal}(1.11,0.0241))$ and calculated the standard deviation of those numbers, which equaled 0.02.
Thus, our prior distribution for $r$ was $\text{Normal}(0.1, 0.02)$.

We chose all other prior distributions to be vague.
However, no prior distribution is completely uninformative, so we made sure that our choice of priors did not have large impacts on posteriors by trying several choices of priors and their associated parameters. 
We then observed their effects on the posteriors (Hobbs and Hooten 2015), which were small.
Our final chosen priors were: $\sigma_{\text{p}} \sim \text{Gamma}(0.01,0.01)$ and $b_{\in{0,1}} \sim \text{Normal}(0,1000)$.


##  Partitioning forecast uncertainty
